apiVersion: v1
kind: Pod
metadata:
  name: testpod2
  namespace: quota-demo
spec:
  containers:
    - name: quota-test
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'echo Pod is Running ; sleep 5000']
      resources:
        requests:
          cpu: "10m"
        limits:
          cpu: "20m"
  restartPolicy: Never